### ISSUE TITLE
SENG201 Assignment

### ISSUE THREAD

**Issue by mch101** [lfa9603/HeroesAndVillains#1]
Hi there,

I noticed that you had a public SENG201 repository on Github- would you be able to make this private, or migrate over to a private Git repository? (such as Gitlab: https://eng-git.canterbury.ac.nz)

This is to reduce the risk of sharing code between teams. If you have any questions, let me know at mch230@uclive.ac.nz

Thanks,
Megan Chu
SENG201 tutor

**Comment by jay-ham1080** [comment]
Hey Megan, 

Sorry about that, we’ll get onto it imediately.

Kind regards,

Jay

Sent from Mail for Windows 10

From: mch101
Sent: Friday, 4 May 2018 9:47 AM
To: lfa9603/HeroesAndVillains
Cc: Subscribed
Subject: [lfa9603/HeroesAndVillains] SENG201 Assignment (#1)

Hi there,
I noticed that you had a public SENG201 repository on Github- would you be able to make this private, or migrate over to a private Git repository? (such as Gitlab: https://eng-git.canterbury.ac.nz)
This is to reduce the risk of sharing code between teams. If you have any questions, let me know at mch230@uclive.ac.nz
Thanks,
Megan Chu
SENG201 tutor

**Comment by lfa9603** [comment]
The repository is now private. Sorry for the inconvenient.
